services:
  server-1:
    build: docker
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: server-1
    secrets:
      - shared-cookie
  server-2:
    build: docker
    hostname: server-2
    secrets:
      - shared-cookie
  server-3:
    build: docker
    hostname: server-3
    secrets:
      - shared-cookie

secrets:
  shared-cookie:
    file: ./docker/shared-cookie
