services:
  server-1:
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_NODENAME: rabbit@server-1
      RABBIT_COOKIE: WERDNGTWUNQDGEWOTCWS
  server-2:
    build: .
    environment:
      RABBITMQ_NODENAME: rabbit@server-2
      RABBIT_COOKIE: WERDNGTWUNQDGEWOTCWS
      NODE_TO_JOIN: rabbit@server-1
    depends_on:
      - server-1
