services:
  server-1:
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: server-1
    environment:
      RABBIT_COOKIE: WERDNGTWUNQDGEWOTCWS
      RUN_CMDS: true
  server-2:
    build: .
    hostname: server-2
    environment:
      RABBIT_COOKIE: WERDNGTWUNQDGEWOTCWS
  server-3:
    build: .
    hostname: server-3
    environment:
      RABBIT_COOKIE: WERDNGTWUNQDGEWOTCWS
