services:
  server-1:
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_NODENAME: rabbit@server-1
      RABBIT_COOKIE: WERDNGTWUNQDGEWOTCWS
      RUN_CMDS: true
  server-2:
    build: .
    environment:
      RABBITMQ_NODENAME: rabbit@server-2
      RABBIT_COOKIE: WERDNGTWUNQDGEWOTCWS
  server-3:
    build: .
    environment:
      RABBITMQ_NODENAME: rabbit@server-3
      RABBIT_COOKIE: WERDNGTWUNQDGEWOTCWS
